backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "Menú de Productos"
    folder: "menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del Producto", name: "title", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Descripción", name: "body", widget: "markdown" }
      - { label: "Imagen del Producto", name: "image", widget: "image", required: false }
